/* 

ESTO TIENE QUE RENDERIZAR MARCADORES EN EL MAPA DONDE SE ENCUENTRAN LAS DEPENDENCIA QUE TIENEN RED POLICIAL.
ADEMAS LOS MARCADORES DEBEN SER DE DIFERENTES COLORES PORQUE DEBERAN DIFERENCIAR EL TIPO DE ENLACE QUE LA DEPENDENCIA TIENE. EJ: 
ENLACE MPLS, HFC, CLARO, EPEC, ADSL, CONECTIVIDAD CORDOBA, OTROS.


CUANDO EL USUARIO TOQUE EL MARCADOR DEBERIA REPRESENTAR UNA VENTANA CON TODA LA INFORMACION DEL MARCADOR
ESTO ES: NOMBRE DE LA DEPENDENCIA, DIRECCION, COORDENEDAS, TIPO DE ENLACE, IP OUTSIDE, IP INSIDE

*/
